### ISSUE TITLE
not working on WHM 11.34.0 (build 9)

### ISSUE THREAD

**Issue by elabda3** [zerosignalproductions/cPanel-2012-Theme#5]
not working on WHM 11.34.0 (build 9)
when i installed it 
i found white page without css

**Comment by zerosignalproductions** [comment]
Sorry, I don't have a way to test on that version. It currently works with WHM 11.38.2 (build 6) but I can't guarantee any other versions. 

I've just updated the theme with a few fixes, so you might try again.
