### ISSUE TITLE
Random pt> code at top of page

### ISSUE THREAD

**Issue by jdolan18** [zerosignalproductions/cPanel-2012-Theme#6]
This shows up in the Branding Editor accessed from WHM. I have all other cpanel styles deactivated and cpanel2012 set as the default cpanel theme for all accounts in my reseller account.
![screen shot 2013-09-05 at 4 35 43 pm](https://f.cloud.github.com/assets/5394608/1091624/074e4d92-166b-11e3-9c48-3a51cbb4330d.png)

It also shows up in the customer cpanel sub pages, such as Email.
![screen shot 2013-09-05 at 4 38 55 pm](https://f.cloud.github.com/assets/5394608/1091646/4e61fc4c-166b-11e3-9af4-29d61c684d14.png)

**Comment by zerosignalproductions** [comment]
I noticed that myself recently. It seems cPanel is duplicating a bit of code for seemingly no reason, or at least not a reason I can tell.

I've messed around with it a bit and have a sloppy fix, but it'll get rid of the pt>. I'll put it up soon.

**Comment by jdolan18** [comment]
Thanks, Justin. Love the theme! Makes my hosting look so much more modern. So thankful!

Jonathan Dolan
918.346.0241

**Comment by zerosignalproductions** [comment]
The theme has been updated along with a couple of extra fixes that I threw in there. Let me know if you see anything else.
