### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by peva3** [zerosignalproductions/cPanel-2012-Theme#7]
I'm really liking this project and would love to see it progress... not really an issue haha.

**Comment by zerosignalproductions** [comment]
If you have any particular updates you'd like to see, just let me know. I'm not particularly active with this, but I'll gladly try to update or fix anything that's requested.

**Comment by peva3** [comment]
Would love to see a cpanel theme that is built around bootstrap, but I know that would be a pretty big undertaking.

**Comment by zerosignalproductions** [comment]
I'd have to look into it a bit more but I know that it's impossible for several of the page templates simply because there's no way to edit them. The index page and a few others I might be able to do. I'll take a look at it thought and see how feasible it is.

**Comment by peva3** [comment]
Another approach would be to check out the in dev x4 theme and maybe try to pull out anything interesting... Idk, just thinking aloud. https://x4demo.cpanel.net:2083/cpsess8715052358/frontend/x4/index.html?post_login=2623545205013

**Comment by zerosignalproductions** [comment]
Nice, I haven't seen the x4 theme yet. Hopefully, they made some improvements to how it's organized. Thanks!

**Comment by peva3** [comment]
np, here's the main page for it, http://themes.cpanel.net/x4/ 

It's been in dev for ages though and I dont think they are planning a full scale release until 2014 or something. So something that looks like it, but also similar to what you're doing here would be really good imo.

**Comment by peva3** [comment]
Any updates? Or changes your are going to be making to the theme? (just curious)

**Comment by zerosignalproductions** [comment]
Well, I've been quite busy lately so I don't think I'm going to get to this any time soon. I did take a look at the x4 theme and it's a pretty big mess, so I'll wait until it's officially released before I decide to use it as a base. Otherwise, I don't have any plans for updates at the moment unless something specific comes up.
