### ISSUE TITLE
problem with icons

### ISSUE THREAD

**Issue by urgido** [zerosignalproductions/cPanel-2012-Theme#9]
Icons have tripled in the style of theme each of this apps has their own icons
![sin ttulo-1](https://f.cloud.github.com/assets/6023013/2221889/b0bf25aa-9a5e-11e3-8926-bcf808bb9dd9.jpg)

**Comment by zerosignalproductions** [comment]
Can you show me what the icons look like without my theme applied?

**Comment by urgido** [comment]
I've changed the theme and then I got back to switch x3 theme with your style and now all is fixed. But now email icons are out of your style.

![sin ttulo](https://f.cloud.github.com/assets/6023013/2236159/0d9ef6b8-9b56-11e3-9ad7-bfa2c27dd9e4.png)

**Comment by zerosignalproductions** [comment]
Sadly that's going to happen for right now because of how cPanel handles icons. In the next update I'm probably going to rollback the custom icons until cPanel releases the updates that will fix the spritesheet issues.

For now, the standard icons will have to do.
